"""Generate revised paper-grade results after workload/SOC corrections."""
from __future__ import annotations

from pathlib import Path
from paths import ensure_output

import numpy as np
import pandas as pd

import model as m
from revised_dispatch import baseline_metrics, solve_revised_dispatch


OUT = ensure_output()


def row(name: str, r: dict) -> dict:
    return {
        "scenario": name,
        "useful_tokens_Mtok": r["useful_tokens_Mtok"],
        "total_cost_usd": r["total_cost_usd"],
        "energy_cost_usd": r["energy_cost_usd"],
        "degradation_cost_usd": r["degradation_cost_usd"],
        "emissions_kg": r["emissions_kg"],
        "usd_per_Mtok": r["usd_per_Mtok"],
        "gco2_per_Mtok": r["gco2_per_Mtok"],
        "peak_grid_kw": r["peak_grid_kw"],
        "evening_grid_kwh": r["evening_grid_kwh"],
        "solve_time_s": r.get("solve_time_s", 0.0),
        "mip_gap": r.get("mip_gap", 0.0),
    }


base = baseline_metrics()
compute = solve_revised_dispatch(no_battery=True)
joint = solve_revised_dispatch()
pd.DataFrame([
    row("BAU", base),
    row("compute_only", compute),
    row("joint_compute_storage", joint),
]).to_csv(OUT / "headline_kpis.csv", index=False)

price, carbon, pv, temp = m.profiles()
hourly = pd.DataFrame({
    "hour": np.arange(m.T_SLOTS),
    "price_usd_kwh": price,
    "carbon_g_kwh": carbon,
    "pv_kw": pv,
    "temperature_c": temp,
    "total_arrivals_Mtok": (
        joint["interactive_arrivals_Mtok"] + joint["batch_arrivals_Mtok"]
    ),
    "interactive_arrivals_Mtok": joint["interactive_arrivals_Mtok"],
    "batch_arrivals_Mtok": joint["batch_arrivals_Mtok"],
    "batch_service_Mtok": joint["batch_service_Mtok"],
    "batch_backlog_Mtok": joint["backlog_Mtok"],
    "level_BAU": base["levels"],
    "level_revised": joint["levels"],
    "grid_BAU_kw": base["grid_kw"],
    "grid_revised_kw": joint["grid_kw"],
    "charge": joint["charge"],
    "discharge": joint["discharge"],
    "soc_start_kwh": joint["soc_kwh"][:-1],
    "soc_end_kwh": joint["soc_kwh"][1:],
})
hourly.to_csv(OUT / "hourly_dispatch.csv", index=False)

# Supported nondominated operating points generated by a weighted-sum carbon
# charge.  The paper calls this a supported trade-off curve, not the complete
# Pareto frontier.
trade_rows = []
for lam_t in [0, 25, 50, 75, 100, 150, 200, 300, 450, 600, 800, 1000,
              1500, 2500, 5000]:
    r = solve_revised_dispatch(carbon_price=lam_t * 1e-6)
    rr = row(f"lambda_{lam_t}", r)
    rr["lambda_usd_tco2"] = lam_t
    trade_rows.append(rr)
pd.DataFrame(trade_rows).to_csv(OUT / "supported_tradeoff.csv", index=False)

# Deadline sensitivity.
delay_rows = []
for delay in [2, 4, 6, 8, 12]:
    r = solve_revised_dispatch(max_batch_delay_h=delay)
    rr = row(f"delay_{delay}h", r)
    rr["max_batch_delay_h"] = delay
    rr["max_backlog_Mtok"] = float(r["backlog_Mtok"].max())
    delay_rows.append(rr)
pd.DataFrame(delay_rows).to_csv(OUT / "deadline_sensitivity.csv", index=False)

# Seasonal PV sensitivity.  These remain illustrative mean-day profiles.
season_rows = []
for name, month in [("Jan", 1), ("Apr", 4), ("Jul", 7), ("Oct", 10)]:
    pv_m = m.pv_profile_kw(month)
    r = solve_revised_dispatch(pv=pv_m)
    b = baseline_metrics()
    # Re-evaluate BAU for the same PV profile.
    load = m.facility_power_kw(m.U_LEVELS[m.BAU_LEVELS], temp)
    grid_b = np.maximum(load - pv_m, 0.0)
    b_cost = float((price * grid_b).sum())
    b_co2 = float((carbon * grid_b).sum() / 1e3)
    season_rows.append({
        "season": name,
        "baseline_cost_usd": b_cost,
        "revised_cost_usd": r["total_cost_usd"],
        "baseline_emissions_kg": b_co2,
        "revised_emissions_kg": r["emissions_kg"],
        "cost_saving_pct": 100.0 * (1.0 - r["total_cost_usd"] / b_cost),
        "emissions_saving_pct": 100.0 * (1.0 - r["emissions_kg"] / b_co2),
    })
pd.DataFrame(season_rows).to_csv(OUT / "seasonal.csv", index=False)

print(pd.read_csv(OUT / "headline_kpis.csv").to_string(index=False))
print(f"Revised data written to {OUT}")
